// Mock video dataset with 12+ distinct videos across diverse genres
export const GENRES = [
  'All',
  'Tech',
  'Music',
  'Gaming',
  'Comedy',
  'Science',
  'Travel',
  'Cooking',
  'Fitness',
  'Design',
];

// Curated color palettes for ambient mode per video
const ambientColors = [
  ['#6366f1', '#8b5cf6', '#06b6d4'],
  ['#ec4899', '#f43f5e', '#f97316'],
  ['#10b981', '#14b8a6', '#06b6d4'],
  ['#f59e0b', '#f97316', '#ef4444'],
  ['#8b5cf6', '#a855f7', '#ec4899'],
  ['#3b82f6', '#6366f1', '#8b5cf6'],
  ['#14b8a6', '#10b981', '#22c55e'],
  ['#f43f5e', '#e11d48', '#be123c'],
  ['#0ea5e9', '#3b82f6', '#6366f1'],
  ['#d946ef', '#a855f7', '#8b5cf6'],
  ['#22c55e', '#16a34a', '#15803d'],
  ['#f97316', '#f59e0b', '#eab308'],
  ['#06b6d4', '#0891b2', '#0e7490'],
  ['#e11d48', '#ec4899', '#f472b6'],
];

export const VIDEOS = [
  {
    id: 'v1',
    title: 'Building a Neural Network from Scratch in Python',
    channel: 'CodeCraft AI',
    channelAvatar: '🤖',
    views: '2.4M views',
    uploadedAt: '3 weeks ago',
    genre: 'Tech',
    youtubeId: 'aircAruvnKk',
    thumbnail: 'https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=640&h=360&fit=crop',
    description: 'Learn how to build a complete neural network from scratch using only Python and NumPy. We cover backpropagation, gradient descent, and activation functions in this comprehensive deep-dive tutorial.',
    ambientColors: ambientColors[0],
    comments: [
      { id: 'c1', user: 'TechWizard42', avatar: '👨‍💻', text: 'This is the best neural network tutorial I have ever seen. Crystal clear explanation!', likes: 342, time: '2 days ago' },
      { id: 'c2', user: 'MLEnthusiast', avatar: '🧠', text: 'Finally someone who explains backpropagation properly. Subscribed!', likes: 187, time: '5 days ago' },
      { id: 'c3', user: 'PythonDev99', avatar: '🐍', text: 'Been coding for 10 years and still learned something new. Great content!', likes: 94, time: '1 week ago' },
    ],
  },
  {
    id: 'v2',
    title: 'Synthwave Chill Mix — Retro Beats for Late Night Coding',
    channel: 'NeonBeats Studio',
    channelAvatar: '🎵',
    views: '8.1M views',
    uploadedAt: '2 months ago',
    genre: 'Music',
    youtubeId: '4xDzrIxZZNE',
    thumbnail: 'https://images.unsplash.com/photo-1614149162883-504ce4d13909?w=640&h=360&fit=crop',
    description: 'Immerse yourself in 1 hour 42 minutes of synthwave and retrowave beats. Perfect background music for coding, studying, or just vibing through the night.',
    ambientColors: ambientColors[1],
    comments: [
      { id: 'c4', user: 'NightOwlCoder', avatar: '🦉', text: 'This is my go-to playlist for every coding session. Absolute perfection.', likes: 1204, time: '3 weeks ago' },
      { id: 'c5', user: 'RetroVibes', avatar: '🌆', text: 'The transition at 45:30 is insane. Chef\'s kiss!', likes: 567, time: '1 month ago' },
    ],
  },
  {
    id: 'v3',
    title: 'Elden Ring DLC — Shadow of the Erdtree Full Walkthrough',
    channel: 'GameMaster Pro',
    channelAvatar: '🎮',
    views: '5.7M views',
    uploadedAt: '1 week ago',
    genre: 'Gaming',
    youtubeId: 'qLZenOn7WUo',
    thumbnail: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=640&h=360&fit=crop',
    description: 'Complete walkthrough of the Elden Ring DLC featuring all bosses, hidden areas, and secret weapons. No spoilers in the thumbnail!',
    ambientColors: ambientColors[2],
    comments: [
      { id: 'c6', user: 'SoulsVeteran', avatar: '⚔️', text: 'That Messmer fight strategy was genius. Saved me hours of suffering.', likes: 890, time: '3 days ago' },
      { id: 'c7', user: 'CasualGamer', avatar: '🕹️', text: 'Finally beat the first boss thanks to this guide!', likes: 234, time: '5 days ago' },
      { id: 'c8', user: 'SpeedRunner', avatar: '🏃', text: 'Skip at 1:23:45 saves about 20 minutes. Great find!', likes: 456, time: '6 days ago' },
    ],
  },
  {
    id: 'v4',
    title: 'When AI Tries to Be a Stand-Up Comedian — Hilarious Results',
    channel: 'LaughFactory Digital',
    channelAvatar: '😂',
    views: '12.3M views',
    uploadedAt: '5 days ago',
    genre: 'Comedy',
    youtubeId: 'O5xeyoRL95U',
    thumbnail: 'https://images.unsplash.com/photo-1527224857830-43a7acc85260?w=640&h=360&fit=crop',
    description: 'We fed the latest AI models classic comedy setups and the results were hilariously unexpected. Watch as artificial intelligence attempts to master the art of humor.',
    ambientColors: ambientColors[3],
    comments: [
      { id: 'c9', user: 'ComedyFan2024', avatar: '🎭', text: 'The knock-knock joke at 7:30 literally had me in tears 😭', likes: 2341, time: '2 days ago' },
      { id: 'c10', user: 'StandUpNerd', avatar: '🎤', text: 'AI comedy > most open mic nights, not gonna lie.', likes: 1567, time: '4 days ago' },
    ],
  },
  {
    id: 'v5',
    title: 'Quantum Computing Explained — From Qubits to Supremacy',
    channel: 'ScienceUnboxed',
    channelAvatar: '🔬',
    views: '3.9M views',
    uploadedAt: '1 month ago',
    genre: 'Science',
    youtubeId: 'JhHMJCUmq28',
    thumbnail: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=640&h=360&fit=crop',
    description: 'Dive deep into the world of quantum computing. We break down quantum mechanics principles, explain how qubits work, and explore what quantum supremacy really means for the future of technology.',
    ambientColors: ambientColors[4],
    comments: [
      { id: 'c11', user: 'PhysicsGeek', avatar: '⚛️', text: 'Best quantum computing explainer on the internet. Period.', likes: 876, time: '2 weeks ago' },
      { id: 'c12', user: 'CSStudent', avatar: '📚', text: 'My professor recommended this video for our quantum computing course!', likes: 543, time: '3 weeks ago' },
    ],
  },
  {
    id: 'v6',
    title: 'Solo Backpacking Through Japan — 30 Days, ¥300,000',
    channel: 'WanderLens',
    channelAvatar: '🌏',
    views: '6.2M views',
    uploadedAt: '2 weeks ago',
    genre: 'Travel',
    youtubeId: '030Gk7OqK2s',
    thumbnail: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=640&h=360&fit=crop',
    description: 'Follow my 30-day solo backpacking adventure through Japan on a budget. From Tokyo\'s neon streets to Kyoto\'s ancient temples, experience the beauty and culture of Japan.',
    ambientColors: ambientColors[5],
    comments: [
      { id: 'c13', user: 'TravelBug', avatar: '✈️', text: 'Added every single recommendation to my Japan itinerary. Thank you!', likes: 1123, time: '1 week ago' },
      { id: 'c14', user: 'BudgetBackpacker', avatar: '🎒', text: 'The capsule hotel review was so helpful. Great budget tips!', likes: 678, time: '10 days ago' },
    ],
  },
  {
    id: 'v7',
    title: 'Gordon Ramsay\'s Ultimate Pasta Masterclass',
    channel: 'ChefStudio Premium',
    channelAvatar: '👨‍🍳',
    views: '15.8M views',
    uploadedAt: '3 months ago',
    genre: 'Cooking',
    youtubeId: 'qPEJgEq3z08',
    thumbnail: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=640&h=360&fit=crop',
    description: 'Master the art of Italian pasta with this comprehensive masterclass. Learn to make fresh pasta dough, three classic sauces, and plating techniques used in Michelin-star restaurants.',
    ambientColors: ambientColors[6],
    comments: [
      { id: 'c15', user: 'HomeCook', avatar: '🍝', text: 'Made the carbonara recipe last night and my family was blown away!', likes: 2345, time: '2 months ago' },
      { id: 'c16', user: 'FoodCritic', avatar: '⭐', text: 'The sauce technique at 15:20 is a game changer. Restaurant quality at home.', likes: 1234, time: '2 months ago' },
    ],
  },
  {
    id: 'v8',
    title: '30-Minute Full Body HIIT — No Equipment Needed',
    channel: 'FitForge',
    channelAvatar: '💪',
    views: '4.5M views',
    uploadedAt: '4 days ago',
    genre: 'Fitness',
    youtubeId: 'ml6cT4AZdqI',
    thumbnail: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=640&h=360&fit=crop',
    description: 'High-intensity interval training workout you can do anywhere with zero equipment. Includes warm-up, 20 exercises, and cool-down stretches. Perfect for beginners to advanced.',
    ambientColors: ambientColors[7],
    comments: [
      { id: 'c17', user: 'FitnessJunkie', avatar: '🏋️', text: 'Day 15 of doing this daily and I can already see results. This works!', likes: 890, time: '2 days ago' },
      { id: 'c18', user: 'NewbieRunner', avatar: '🏃‍♀️', text: 'Love that you show modifications for beginners. So inclusive!', likes: 567, time: '3 days ago' },
    ],
  },
  {
    id: 'v9',
    title: 'Designing a Complete Brand Identity in Figma — Start to Finish',
    channel: 'DesignLab',
    channelAvatar: '🎨',
    views: '1.8M views',
    uploadedAt: '6 days ago',
    genre: 'Design',
    youtubeId: 'c9Wg6Cb_YlU',
    thumbnail: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=640&h=360&fit=crop',
    description: 'Watch the complete process of designing a professional brand identity from scratch in Figma. Covers logo design, color palette selection, typography, and brand guidelines document creation.',
    ambientColors: ambientColors[8],
    comments: [
      { id: 'c19', user: 'UIDesigner', avatar: '✨', text: 'This is basically a $500 course for free. Incredible value!', likes: 1456, time: '3 days ago' },
      { id: 'c20', user: 'StartupFounder', avatar: '🚀', text: 'Used this to design my startup\'s brand. Saved thousands on a designer.', likes: 789, time: '5 days ago' },
    ],
  },
  {
    id: 'v10',
    title: 'The Rise of Rust — Why Developers Are Switching',
    channel: 'DevInsider',
    channelAvatar: '🦀',
    views: '3.1M views',
    uploadedAt: '10 days ago',
    genre: 'Tech',
    youtubeId: '5C_HPTJg5ek',
    thumbnail: 'https://images.unsplash.com/photo-1629654297299-c8506221ca97?w=640&h=360&fit=crop',
    description: 'Explore why Rust is rapidly becoming the language of choice for systems programming. We analyze performance benchmarks, memory safety guarantees, and real-world adoption stories from major tech companies.',
    ambientColors: ambientColors[9],
    comments: [
      { id: 'c21', user: 'RustaceanPro', avatar: '🦀', text: 'Been using Rust for 3 years and can\'t go back to C++. The compiler is your best friend!', likes: 1234, time: '1 week ago' },
      { id: 'c22', user: 'GoLangFan', avatar: '🐹', text: 'Great comparison! I still prefer Go for web services but Rust is unbeatable for systems.', likes: 567, time: '9 days ago' },
    ],
  },
  {
    id: 'v11',
    title: 'Lo-fi Jazz Beats — Study & Relaxation Mix',
    channel: 'ChillHarbor',
    channelAvatar: '🎷',
    views: '22.4M views',
    uploadedAt: '6 months ago',
    genre: 'Music',
    youtubeId: 'jfKfPfyJRdk',
    thumbnail: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=640&h=360&fit=crop',
    description: 'Over two hours of smooth lo-fi jazz beats blended with ambient rain sounds. The perfect companion for late-night study sessions, creative work, or unwinding after a long day.',
    ambientColors: ambientColors[10],
    comments: [
      { id: 'c23', user: 'StudyBuddy', avatar: '📖', text: 'I literally passed my finals because of this playlist. Not even joking.', likes: 4567, time: '4 months ago' },
      { id: 'c24', user: 'MusicLover', avatar: '🎶', text: 'The sax solo at 1:12:00 is pure magic. Who is that musician?', likes: 2345, time: '5 months ago' },
    ],
  },
  {
    id: 'v12',
    title: 'Minecraft Mega Base Build — 200 Hours Timelapse',
    channel: 'BlockCraft Studios',
    channelAvatar: '⛏️',
    views: '9.3M views',
    uploadedAt: '3 days ago',
    genre: 'Gaming',
    youtubeId: 'w3lX6Z32aO8',
    thumbnail: 'https://images.unsplash.com/photo-1587573089734-599d584d8eff?w=640&h=360&fit=crop',
    description: 'Watch 200 hours of building compressed into a 35-minute timelapse. This massive medieval castle mega base features working redstone mechanisms, custom terraforming, and interior design in survival mode.',
    ambientColors: ambientColors[11],
    comments: [
      { id: 'c25', user: 'MinecraftPro', avatar: '🏰', text: 'The attention to detail is insane. That chandelier design is next level!', likes: 3456, time: '1 day ago' },
      { id: 'c26', user: 'RedstoneWizard', avatar: '🔴', text: 'The hidden piston door mechanism at 22:15 is genius. Tutorial please!', likes: 1890, time: '2 days ago' },
    ],
  },
  {
    id: 'v13',
    title: 'The Science of Black Holes — What Happens Beyond the Event Horizon',
    channel: 'CosmosDeep',
    channelAvatar: '🌌',
    views: '7.8M views',
    uploadedAt: '2 weeks ago',
    genre: 'Science',
    youtubeId: 'yWO-cvGETRQ',
    thumbnail: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=640&h=360&fit=crop',
    description: 'Journey into the most mysterious objects in the universe. This documentary-style video explores singularities, spaghettification, Hawking radiation, and the information paradox with stunning visualizations.',
    ambientColors: ambientColors[12],
    comments: [
      { id: 'c27', user: 'AstroNerd', avatar: '🔭', text: 'The visualization of gravitational lensing was mind-blowing. Best space content!', likes: 2345, time: '1 week ago' },
      { id: 'c28', user: 'SpaceEngineer', avatar: '🚀', text: 'As an astrophysicist, I appreciate how accurately this is presented. Well done!', likes: 1678, time: '10 days ago' },
    ],
  },
  {
    id: 'v14',
    title: 'Street Food Tour — Bangkok After Midnight',
    channel: 'FoodNomad',
    channelAvatar: '🍜',
    views: '4.2M views',
    uploadedAt: '8 days ago',
    genre: 'Travel',
    youtubeId: '77bJ_O3rR9I',
    thumbnail: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=640&h=360&fit=crop',
    description: 'Explore Bangkok\'s vibrant night food scene. From sizzling pad thai stalls to secret late-night dessert spots, discover the best street food the city has to offer after midnight.',
    ambientColors: ambientColors[13],
    comments: [
      { id: 'c29', user: 'FoodieExplorer', avatar: '🍱', text: 'That pad kra pao stall at 12:30 is now on my bucket list!', likes: 1456, time: '5 days ago' },
      { id: 'c30', user: 'ThailandFan', avatar: '🇹🇭', text: 'I know that exact stall at Yaowarat! Best in Bangkok, confirmed!', likes: 890, time: '7 days ago' },
    ],
  },
];

// Search suggestions for the dynamic search bar
export const SEARCH_SUGGESTIONS = [
  'React tutorial for beginners',
  'Best synthwave playlist 2024',
  'Elden Ring boss guide',
  'Python machine learning',
  'How to cook pasta',
  'HIIT workout at home',
  'Figma design tutorial',
  'Rust programming language',
  'Lo-fi study music',
  'Minecraft building ideas',
  'Quantum computing basics',
  'Japan travel vlog',
  'AI comedy show',
  'Black hole documentary',
  'Bangkok street food',
  'Brand identity design',
  'Neural network from scratch',
  'Full body workout no equipment',
  'Gaming walkthrough',
  'Science documentary',
];
